Sistema-Ecommerce/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EComemerce_01.Models
{
    public class Supplier
    {
        [Key]
        public int SupplierId { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [MaxLength(256, ErrorMessage = "El campo {0} debe tener {1} caracteres de longitud como maximo")]
        [Display(Name = "E-mail")]
        [DataType(DataType.EmailAddress)]
        public string UserName { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [MaxLength(50, ErrorMessage = "El campo {0} debe tener {1} caracteres de longitud como maximo")]
        [Display(Name = "Apellidos")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [MaxLength(50, ErrorMessage = "El campo {0} debe tener {1} caracteres de longitud como maximo")]
        [Display(Name = "Nombres")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [MaxLength(20, ErrorMessage = "El campo {0} debe tener {1} caracteres de longitud como maximo")]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Telefono")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [MaxLength(100, ErrorMessage = "El campo {0} debe tener {1} caracteres de longitud como maximo")]
        [Display(Name = "Direccion")]
        public string Adress { get; set; }

        [DataType(DataType.ImageUrl)]
        [Display(Name = "Foto")]
        public string Photo { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Range(1, double.MaxValue, ErrorMessage = "Seleccionar un {0}")]
        [Display(Name = "Departamento")]
        public int DepartmentId { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Range(1, double.MaxValue, ErrorMessage = "Seleccionar un {0}")]
        [Display(Name = "Ciudad")]
        public int CityId { get; set; }

        [Display(Name = "Proveedor")]
        
        public string FullName { get { return string.Format("{0} {1}", FirstName, LastName); } }

        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }

        public virtual Department Department { get; set; }
        public virtual City City { get; set; }

        public virtual ICollection<CompanySupplier> CompanySuppliers { get; set; }

    }
}

Sistema-Ecommerce/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EComemerce_01.Models;
using EComemerce_01.Classes;
using PagedList;

namespace EComemerce_01.Controllers
{
    [Authorize(Roles = "User")]
    public class SuppliersController : Controller
    {
        private ECommerceContext db = new ECommerceContext();

        // GET: Suppliers
        public ActionResult Index(int? page = null,string buscarCategoria = null)
        {
            page = (page ?? 1);
            var user = db.User.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();

            var qry = (from cu in db.Suppliers
                       join cc in db.CompanySuppliers on cu.SupplierId equals cc.SupplierId
                       join co in db.Companies on cc.CompanyId equals co.CompanyId
                       where co.CompanyId == user.CompanyId
                       select new { cu }).ToList();

            var suppliers = new List<Supplier>();

            foreach (var item in qry)
            {
                suppliers.Add(item.cu);
            }

            if (!string.IsNullOrEmpty(buscarCategoria))
            {
                suppliers = suppliers.Where(s => s.FullName.ToUpper().Contains(buscarCategoria.ToUpper())
                       || s.Adress.ToUpper().Contains(buscarCategoria.ToUpper())
                       || s.Phone.ToUpper().Contains(buscarCategoria.ToUpper())
                       || s.City.Name.ToUpper().Contains(buscarCategoria.ToUpper())
                       || s.Department.Name.ToUpper().Contains(buscarCategoria.ToUpper())
                       || s.UserName.ToUpper().Contains(buscarCategoria.ToUpper())).ToList();

            }



            return View(suppliers.ToPagedList((int)page, 5));
        }

        // GET: Suppliers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        // GET: Suppliers/Create
        public ActionResult Create()
        {
            ViewBag.CityId = new SelectList(CombosHelper.GetCities(0), "CityId", "Name");
            ViewBag.DepartmentId = new SelectList(CombosHelper.GetDepartments(), "DepartmentId", "Name");
            return PartialView();
        }

        // POST: Suppliers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        db.Suppliers.Add(supplier);
                        var response = DBHelper.SaveChanges(db);
                        if (!response.Succeeded)
                        {
                            ModelState.AddModelError(string.Empty, response.Message);
                            transaction.Rollback();
                            ViewBag.CityId = new SelectList(CombosHelper.GetCities(supplier.DepartmentId), "CityId", "Name", supplier.CityId);
                            ViewBag.DepartmentId = new SelectList(CombosHelper.GetDepartments(), "DepartmentId", "Name", supplier.DepartmentId);
                            return View(supplier);
                        }
                        UserHelper.CreateUserASP(supplier.UserName, "Supplier");
                        if (supplier.PhotoFile != null)
                        {

                            var folder = "~/Content/Suppliers";
                            var file = string.Format("{0}.jpg", supplier.SupplierId);
                            var resp= FilesHelper.UploadPhoto(supplier.PhotoFile, folder, file);
                            if (resp)
                            {
                                var pic = string.Format("{0}/{1}", folder, file);
                                supplier.Photo = pic;
                                db.Entry(supplier).State = EntityState.Modified;
                                db.SaveChanges();
                            }

                        }

                        var user = db.User.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
                        var companySupplier = new CompanySupplier
                        {
                            CompanyId = user.CompanyId,
                            SupplierId = supplier.SupplierId
                        };

                        db.CompanySuppliers.Add(companySupplier);
                        db.SaveChanges();
                        transaction.Commit();
                        return Json(new { success = true });

                    }
                    catch (Exception ex)
                    { 
                    
                        transaction.Rollback();
                        ModelState.AddModelError(string.Empty, ex.Message);

                    }
                }
            }

            ViewBag.CityId = new SelectList(CombosHelper.GetCities(supplier.DepartmentId), "CityId", "Name", supplier.CityId);
            ViewBag.DepartmentId = new SelectList(CombosHelper.GetDepartments(), "DepartmentId", "Name", supplier.DepartmentId);
            return PartialView(supplier);
        }

        // GET: Suppliers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityId = new SelectList(CombosHelper.GetCities(supplier.DepartmentId), "CityId", "Name", supplier.CityId);
            ViewBag.DepartmentId = new SelectList(CombosHelper.GetDepartments(), "DepartmentId", "Name", supplier.DepartmentId);
            return PartialView(supplier);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                if (supplier.PhotoFile != null)
                {
                    var file = string.Format("{0}.jpg", supplier.SupplierId);
                    var folder = "~/Content/Suppliers";
                    var resp = FilesHelper.UploadPhoto(supplier.PhotoFile, folder, file);
                    supplier.Photo = string.Format("{0}/{1}", folder, file);    
                }

                db.Entry(supplier).State = EntityState.Modified;
                db.SaveChanges();
                var response = DBHelper.SaveChanges(db);
                if (response.Succeeded)
                {

                    return Json(new { success = true });
                }
                ModelState.AddModelError(string.Empty, response.Message);
            }
            ViewBag.CityId = new SelectList(CombosHelper.GetCities(supplier.DepartmentId), "CityId", "Name", supplier.CityId);
            ViewBag.DepartmentId = new SelectList(CombosHelper.GetDepartments(), "DepartmentId", "Name", supplier.DepartmentId);
            return PartialView(supplier);
        }

        // GET: Suppliers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var supplier = db.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return PartialView(supplier);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var supplier = db.Suppliers.Find(id);
            var user = db.User.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
            var companySupplier = db.CompanySuppliers.Where(cc => cc.CompanyId == user.CompanyId && cc.SupplierId == supplier.SupplierId).FirstOrDefault();

            using (var transaction = db.Database.BeginTransaction())
            {
                db.CompanySuppliers.Remove(companySupplier);
                db.Suppliers.Remove(supplier);
                var response = DBHelper.SaveChanges(db);

                if (response.Succeeded)
                {
                    transaction.Commit();
                    return Json(new { success = true });
                }
                transaction.Rollback();
                ModelState.AddModelError(string.Empty, response.Message);
                return PartialView(supplier);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sistema-Ecommerce/Views/Suppliers/Create.cshtml
@model EComemerce_01.Models.Supplier

@{
    ViewBag.Title = "Crear";
}

    <script src="~/Scripts/ecommerce.js"></script>
    <script src="~/Scripts/fileupload.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        var Url = '@Url.Action("GetCities", "Generic")';
    </script>
<section id="formularios">
    @using (Html.BeginForm("Create", "Suppliers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <br />
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })                   
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Adress, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    <div class="file-input-new">
                        <div class="input-group" style="width:280px">
                            <div tabindex="500" class="form-control file-caption">
                                <div class="file-caption-name" id="NombreArchivo">
                                </div>
                            </div>
                            <div class="input-group-btn" style="height:auto">
                                <div tabindex="500" class="btn btn-primary btn-file">
                                    <i class="fa fa-fw fa-folder-open"></i>
                                    File Search...
                                    @Html.TextBoxFor(modelo => modelo.PhotoFile, new { type = "file", id = "files" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control" })                  
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="text-right"style="margin-right:110px">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                    @Html.ActionLink("Regresar", "Index", new { }, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    }
</section>


Sistema-Ecommerce/Views/Suppliers/Delete.cshtml
@model EComemerce_01.Models.Supplier

@{
    ViewBag.Title = "Eliminar Proveedor";
}
@Scripts.Render("~/bundles/jqueryval")
<section>
    <div class="modal-shadow text-center">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="panel-body">
            <div class="form-group">
                <div class="text-center">
                    ¿Está seguro de querer eliminar este proveedor:
                </div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <div>
                        <input type="submit" value="Eliminar" class="btn btn-primary" />
                        @Html.ActionLink("Regresar", "Index", new { }, new { @class = "btn btn-success" })
                    </div>
                </div>
            }
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}


Sistema-Ecommerce/Views/Suppliers/Details.cshtml
@model EComemerce_01.Models.Supplier

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Proveedores</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.City.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.SupplierId }) |
    @Html.ActionLink("Atras", "Index")
</p>

Sistema-Ecommerce/Views/Suppliers/Edit.cshtml
@model EComemerce_01.Models.Supplier

@{
    ViewBag.Title = "Editar";
}

    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ecommerce.js"></script>
    <script src="~/Scripts/fileupload.js"></script>
    <script type="text/javascript">
        var Url = '@Url.Action("GetCities", "Generic")';
    </script>
<section id="formularios">
    @using (Html.BeginForm("Edit", "Suppliers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <br />
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.SupplierId)

            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })                   
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Adress, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    <div class="file-input-new">
                        <div class="input-group" style="width:280px">
                            <div tabindex="500" class="form-control file-caption">
                                <div class="file-caption-name" id="NombreArchivo">
                                </div>
                            </div>
                            <div class="input-group-btn" style="height:auto">
                                <div tabindex="500" class="btn btn-primary btn-file">
                                    <i class="fa fa-fw fa-folder-open"></i>
                                    File Search...
                                    @Html.TextBoxFor(modelo => modelo.PhotoFile, new { type = "file", id = "files" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })
                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="text-right">
                    @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control" })                    
                </div>
                <div class="text-center">
                    @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group"style="margin-right:110px">
                <div class="text-right">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                    @Html.ActionLink("Regresar", "Index", new { }, new { @class = "btn btn-success" })
                </div>
            </div>
        </div>
    }
</section>


Sistema-Ecommerce/Views/Suppliers/Index.cshtml
@model PagedList.IPagedList<EComemerce_01.Models.Supplier>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Proveedores";
}
<body class="container body-content">
    <h2>Proveedores</h2>

    @using (Html.BeginForm())
    {
        <table>
            <tr>
                <td>
                    @Html.TextBox("buscarCategoria", ViewBag.CurrentSearch as string, new { @class = "form-control" })
                </td>
                <td>
                    <input type="submit" value="Buscar" class="btn btn-primary" />
                </td>
                <td>
                    @Html.ActionLink("Nuevo", "Create", new { }, new { @class = "btn btn-primary", data_modal = "" })
                </td>
            </tr>
        </table>
    }
    <br />

    <table class="table table-bordered">
        <tr class="success">
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.FirstOrDefault().City.Name)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.FirstOrDefault().Department.Name)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.FirstOrDefault().UserName)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.FirstOrDefault().FirstName)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.FirstOrDefault().LastName)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.FirstOrDefault().Phone)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.FirstOrDefault().Adress)
            </th>
            <th style="text-align:center">
                @Html.DisplayNameFor(model => model.FirstOrDefault().Photo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.City.Name)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Department.Name)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.Adress)
                </td>
                <td style="text-align:center">
                    @if (!string.IsNullOrEmpty(item.Photo))
                    {
                        <img src="@Url.Content(item.Photo)" alt="Image" style="width:100px;height:100px;max-width: 100%; height: auto;" />
                    }
                </td>
                <td style="text-align:center">
                    @Html.ActionLink("Editar", "Edit", new { id = item.SupplierId }, new { @class = "btn btn-warning", data_modal = "" })
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.SupplierId }, new { @class = "btn btn-success", data_modal = "" })
                </td>
            </tr>
        }

    </table>
    Página: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber), de: @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page,
    sortOrder =
    ViewBag.CurrentSort,
    currentFilter = ViewBag.CurrentFilter
}))

</body>

